### ISSUE TITLE
이벤트 페이지 퍼블리싱 ~9/23

### ISSUE THREAD

**Issue by davidktlee** [IKO-FinalProject/FE-Client#55]
## Description

이벤트 페이지 및 이벤트 상세 페이지 퍼블리싱

## To-do

- [x] 메인 페이지에서의 이벤트 페이지 퍼블리싱
- [x] 이벤트 페이지 퍼블리싱
- [x] 이벤트 상세 페이지 퍼블리싱
