### ISSUE TITLE
모바일 필터

### ISSUE THREAD

**Issue by GyeongChan-Jang** [IKO-FinalProject/FE-Client#75]
## Description

필터 모바일 구현

## To-do

- [x] 필터 모바일 구현
- [x] 필터 버튼 누르면 open
- [x] open시 애니메이션 적용

## ETC
필터 값을 state값으로 누적 적용하는 것은 아직 구현X
